### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by ghost** [superzackx/VoiceActivatedBots#1]
# Variable Scopes
I hope you know that in Vanilla Javascript, the `var` keyword is at local scope. Inside of functions using vars is just silly because you don't want it in other parts of your code. Using the `let` keyword inside your functions would be better.

Also inside functions you would not need any arguments if you replace var with const. That way it would be cleaner and better for people like me to read. (I am not the best at JS, but heres a suggestion)

Thanks and Regards,
NightZan999

**Comment by superzackx** [comment]
Cool, I'll work on the feedback.
